# -*- coding: utf-8 -*-

"""Public API, data contracts, and readers for EOS workflows."""

from quantas.core.math.fitting import odr_backend_available

from .api import EOSFitter
from .contracts import (
    EOSCapabilityStatus,
    EOSDomainCapability,
    EOSModuleContract,
    EOS_DOMAIN_CAPABILITIES,
    eos_domain_capability,
)
from .facade import (
    MODULE_CONTRACT,
    build_eos_plots,
    calculate_eos,
    diagnose_eos,
    fit_eos,
    open_eos_archive,
)
from .batch import (
    EOSBatchFailurePolicy,
    EOSBatchJob,
    EOSBatchJobResult,
    EOSBatchPlan,
    EOSBatchResult,
    EOSBatchWorkflow,
    run_eos_batch,
)
from .archive import EOSArchive, infer_result_slots
from .calculator import EOSCalculationResult, EOSCalculator
from .diagnostics import EOSDiagnosticResult, EOSDiagnostics
from .domains.pv import (
    AxialEOSFitModel,
    PressureEOSFitModel,
    axial_to_volume_parameters,
    build_axial_parameter_map,
    build_pressure_parameter_map,
    estimate_axial_parameters,
    estimate_pressure_parameters,
)
from .io import EOSInputFileReader, read_eos_input
from .report import (
    EOSReportDetail,
    EOSReportOptions,
    build_eos_batch_preamble,
    build_eos_batch_report,
    build_eos_batch_result_tables,
    eos_batch_fit_summary_table,
    eos_batch_parameter_summary_table,
    eos_data_selection_table,
    eos_data_table,
    eos_uncertainty_table,
)
from .plot import EOS_PLOT_TYPES, EOSPlotOptions, EOSPlotter
from .postfit import (
    eos_calculation_summary_table,
    eos_calculation_table,
    eos_diagnostic_summary_table,
    eos_diagnostic_table,
    write_eos_calculation_csv,
    write_eos_diagnostic_csv,
)
from .domains.pvt import (
    PVTEOSFitModel,
    build_pvt_parameter_map,
    estimate_pvt_parameters,
    pvt_parameter_names,
)
from .spec import (
    EOS_SPEC_SIGNATURE,
    EOS_SPEC_VERSION,
    EOSResolvedSpec,
    EOSSpecDocument,
    EOSSpecError,
    EOSSpecInputOptions,
    canonical_eos_parameter_name,
    parse_eos_spec,
    read_eos_spec,
    resolve_eos_spec,
)
from .spec_template import (
    EOS_SPEC_TEMPLATE_FILENAME,
    eos_spec_template,
    write_eos_spec_template,
)
from .domains.vt import (
    TemperatureEOSFitModel,
    build_temperature_parameter_map,
    estimate_temperature_parameters,
    temperature_parameter_names,
)
from .history import (
    EOSFitRecord,
    EOSResultSlot,
    EOSSlotState,
    EOSSlotStatus,
    EOSStateEvent,
    EOSStateEventType,
)
from .inspection import (
    EOSArchiveInspection,
    EOSArchiveSizeInfo,
    EOSRecordDisposition,
    EOSRecordInspection,
    EOSSlotInspection,
)
from .models import (
    EOSCoordinateProfile,
    EOSCoordinateVariation,
    EOSCrystalSystem,
    EOSDataset,
    EOSDatasetClassification,
    EOSFitDomain,
    EOSFitOptions,
    EOSFitRequest,
    EOSFitResult,
    EOSSeries,
    ParameterConstraint,
    parse_eos_crystal_system,
)
from .session import EOSSession

__all__ = [
    "MODULE_CONTRACT",
    "EOSCapabilityStatus",
    "EOSDomainCapability",
    "EOSModuleContract",
    "EOS_DOMAIN_CAPABILITIES",
    "AxialEOSFitModel",
    "EOSBatchFailurePolicy",
    "EOSBatchJob",
    "EOSBatchJobResult",
    "EOSBatchPlan",
    "EOSBatchResult",
    "EOSBatchWorkflow",
    "EOSArchive",
    "EOSArchiveInspection",
    "EOSArchiveSizeInfo",
    "EOSCalculationResult",
    "EOSCalculator",
    "EOSCoordinateProfile",
    "EOSCoordinateVariation",
    "EOSCrystalSystem",
    "EOSDataset",
    "EOSDatasetClassification",
    "EOSDiagnosticResult",
    "EOSDiagnostics",
    "EOSFitDomain",
    "EOSFitRecord",
    "EOSFitOptions",
    "EOSFitRequest",
    "EOSFitResult",
    "EOSFitter",
    "EOSInputFileReader",
    "EOS_PLOT_TYPES",
    "EOSPlotOptions",
    "EOSPlotter",
    "EOSReportDetail",
    "EOSReportOptions",
    "EOSRecordDisposition",
    "EOSRecordInspection",
    "EOSResolvedSpec",
    "EOSSpecDocument",
    "EOSSpecError",
    "EOSSpecInputOptions",
    "EOS_SPEC_SIGNATURE",
    "EOS_SPEC_VERSION",
    "EOS_SPEC_TEMPLATE_FILENAME",
    "EOSResultSlot",
    "EOSSeries",
    "EOSSession",
    "EOSSlotInspection",
    "EOSSlotState",
    "EOSSlotStatus",
    "EOSStateEvent",
    "EOSStateEventType",
    "ParameterConstraint",
    "PressureEOSFitModel",
    "PVTEOSFitModel",
    "TemperatureEOSFitModel",
    "axial_to_volume_parameters",
    "build_eos_batch_preamble",
    "build_eos_batch_report",
    "build_eos_batch_result_tables",
    "eos_batch_fit_summary_table",
    "eos_batch_parameter_summary_table",
    "build_axial_parameter_map",
    "build_pressure_parameter_map",
    "build_pvt_parameter_map",
    "build_temperature_parameter_map",
    "canonical_eos_parameter_name",
    "estimate_axial_parameters",
    "estimate_pressure_parameters",
    "estimate_pvt_parameters",
    "estimate_temperature_parameters",
    "eos_calculation_summary_table",
    "eos_calculation_table",
    "eos_diagnostic_summary_table",
    "eos_diagnostic_table",
    "eos_data_selection_table",
    "eos_data_table",
    "eos_spec_template",
    "eos_uncertainty_table",
    "infer_result_slots",
    "odr_backend_available",
    "parse_eos_crystal_system",
    "parse_eos_spec",
    "read_eos_spec",
    "resolve_eos_spec",
    "pvt_parameter_names",
    "read_eos_input",
    "run_eos_batch",
    "temperature_parameter_names",
    "write_eos_calculation_csv",
    "write_eos_diagnostic_csv",
    "write_eos_spec_template",
    "build_eos_plots",
    "calculate_eos",
    "diagnose_eos",
    "eos_domain_capability",
    "fit_eos",
    "open_eos_archive",
]
