language: python            # ok on Linux, but it is an error on macOS or Windows
matrix:
    include:
        - name: "Python 3.5 on Xenial Linux"
          python: 3.5
        - name: "Python 3.6 on Xenial Linux"
          python: 3.6
        - name: "Python 3.7 on Xenial Linux"
          python: 3.7
        - name: "Python 3.8 on Xenial Linux"
          python: 3.8
        - name: "Python 3.7.2 on macOS"
          os: osx
          osx_image: xcode11
          language: shell
          before_install: python3 --version ; pip3 --version ; sw_vers ; pip3 install pytest
install:
    pip3 install --upgrade pip ; pip3 install -r requirements.txt ; pip3 install --editable .
script: python3 -m pytest || python -m pytest