# -*- coding: utf-8 -*-

"""Shared elasticity models and numerical operations."""

from .adiabatic import (
    AdiabaticStiffnessFieldResult,
    adiabatic_stiffness_field,
    thermal_expansion_tensor_to_voigt,
)
from .averages import (
    ElasticAverages,
    IsotropicElasticProperties,
    compute_elastic_averages,
)
from .conventions import (
    ENGINEERING_SHEAR_FACTORS,
    VOIGT_INDEX_MAP,
    VOIGT_LABELS,
    VOIGT_PAIRS,
    cartesian_compliance_to_voigt,
    cartesian_stiffness_to_voigt,
    rotate_voigt_stiffness,
    voigt_compliance_to_cartesian,
    voigt_stiffness_to_cartesian,
)
from .directional import (
    direction_vector,
    linear_compressibility,
    poisson_ratio,
    sample_linear_compressibility,
    sample_poisson_ratio,
    sample_shear_modulus,
    sample_young_modulus,
    shear_modulus,
    transverse_poisson_extrema,
    transverse_shear_extrema,
    young_modulus,
)
from .extrema import DirectionalExtrema, find_directional_extrema
from .quasistatic import (
    cold_finite_strain_component,
    cold_finite_strain_component_jacobian,
    FiniteStrainOrder,
    cold_finite_strain_stiffness,
    eulerian_finite_strain,
    wallace_hydrostatic_delta_voigt,
)
from .prestress import (
    correct_hydrostatic_elastic_series,
    correct_hydrostatic_elastic_state,
    hydrostatic_wallace_stiffness,
)
from .sampling import (
    SUPPORTED_DIRECTIONAL_PROPERTIES,
    ElasticDirectionalField,
    ElasticDirectionalProperty,
    ElasticSamplingDiagnostics,
    ExactTransverseExtrema,
    exact_transverse_extrema,
    sample_elastic_directional_field,
)
from .stability import (
    StabilityFieldResult,
    StabilityResult,
    check_positive_definiteness,
    evaluate_stability_field,
)
from .surface import (
    SUPPORTED_SURFACE_PROPERTIES,
    DirectionalSurface,
    ElasticitySurfaceCollection,
    ElasticSurfaceProperty,
    TransverseExtrema,
    sample_elasticity_surfaces,
    transverse_extrema,
)
from .symmetry import (
    ElasticComponentDefinition,
    elastic_component_definitions,
    extract_independent_stiffness_components,
    reconstruct_stiffness_from_components,
    stiffness_component_linear_coefficients,
    ELASTIC_SYMMETRY_PATTERNS,
    detect_elastic_symmetry,
    is_elastic_symmetry,
    specialize_elastic_tensor,
)
from .tensor import ElasticTensor, OrthorhombicElasticTensor
from .validation import (
    DEFAULT_STIFFNESS_SYMMETRY_TOLERANCE,
    StiffnessSymmetryCriterion,
    invert_stiffness_matrix,
    stiffness_maximum_asymmetry,
    stiffness_symmetry_residual,
    validate_stiffness_matrix,
)

__all__ = [
    "AdiabaticStiffnessFieldResult",
    "adiabatic_stiffness_field",
    "thermal_expansion_tensor_to_voigt",
    "DEFAULT_STIFFNESS_SYMMETRY_TOLERANCE",
    "DirectionalExtrema",
    "DirectionalSurface",
    "SUPPORTED_DIRECTIONAL_PROPERTIES",
    "ExactTransverseExtrema",
    "ElasticSamplingDiagnostics",
    "ElasticDirectionalProperty",
    "ElasticDirectionalField",
    "ELASTIC_SYMMETRY_PATTERNS",
    "ENGINEERING_SHEAR_FACTORS",
    "ElasticAverages",
    "FiniteStrainOrder",
    "ElasticSurfaceProperty",
    "ElasticTensor",
    "ElasticitySurfaceCollection",
    "IsotropicElasticProperties",
    "OrthorhombicElasticTensor",
    "SUPPORTED_SURFACE_PROPERTIES",
    "StabilityFieldResult",
    "StabilityResult",
    "StiffnessSymmetryCriterion",
    "TransverseExtrema",
    "VOIGT_INDEX_MAP",
    "VOIGT_LABELS",
    "VOIGT_PAIRS",
    "cartesian_compliance_to_voigt",
    "cartesian_stiffness_to_voigt",
    "check_positive_definiteness",
    "evaluate_stability_field",
    "compute_elastic_averages",
    "correct_hydrostatic_elastic_series",
    "correct_hydrostatic_elastic_state",
    "cold_finite_strain_component",
    "cold_finite_strain_component_jacobian",
    "cold_finite_strain_stiffness",
    "eulerian_finite_strain",
    "ElasticComponentDefinition",
    "detect_elastic_symmetry",
    "elastic_component_definitions",
    "extract_independent_stiffness_components",
    "direction_vector",
    "find_directional_extrema",
    "sample_elastic_directional_field",
    "exact_transverse_extrema",
    "invert_stiffness_matrix",
    "hydrostatic_wallace_stiffness",
    "is_elastic_symmetry",
    "linear_compressibility",
    "poisson_ratio",
    "reconstruct_stiffness_from_components",
    "stiffness_component_linear_coefficients",
    "rotate_voigt_stiffness",
    "sample_elasticity_surfaces",
    "sample_linear_compressibility",
    "sample_poisson_ratio",
    "sample_shear_modulus",
    "sample_young_modulus",
    "shear_modulus",
    "specialize_elastic_tensor",
    "stiffness_symmetry_residual",
    "stiffness_maximum_asymmetry",
    "transverse_extrema",
    "transverse_poisson_extrema",
    "transverse_shear_extrema",
    "validate_stiffness_matrix",
    "voigt_compliance_to_cartesian",
    "voigt_stiffness_to_cartesian",
    "wallace_hydrostatic_delta_voigt",
    "young_modulus",
]
