# -*- coding: utf-8 -*-

"""Literal CRYSTAL output markers shared by interface parsers.

Only strings that are actively interpreted by Quantas belong here. Structured
records whose values are extracted with regular expressions live in
:mod:`quantas.interfaces.crystal.patterns` instead.
"""

from __future__ import annotations

from typing import Final


# Geometry
GEOMETRY_CONSISTENT: Final[str] = "GEOMETRY NOW FULLY CONSISTENT WITH THE GROUP"
GEOMETRY_WAVEFUNCTION: Final[str] = "GEOMETRY FOR WAVE FUNCTION -"
FINAL_OPTIMIZED_GEOMETRY: Final[str] = "FINAL OPTIMIZED GEOMETRY"
PRIMITIVE_CELL: Final[str] = "PRIMITIVE CELL -"
SUPERCELL_OPTION: Final[str] = "* SUPERCELL OPTION"
SUPERCELL_EXPANSION: Final[str] = "EXPANSION MATRIX OF PRIMITIVE CELL"
DIRECT_LATTICE_VECTORS: Final[str] = "DIRECT LATTICE VECTORS"
PRIMITIVE_TO_CRYSTALLOGRAPHIC: Final[str] = (
    "TRANSFORMATION MATRIX PRIMITIVE-CRYSTALLOGRAPHIC CELL"
)

# Phonons
FREQUENCY_CALCULATION: Final[str] = (
    "EIGENVALUES (EIGV) OF THE MASS WEIGHTED HESSIAN MATRIX AND HARMONIC"
)
SCELPHONO_OPTION: Final[str] = (
    "PHONON FREQUENCIES AT A SET OF K POINTS BY USING A SUPERCELL"
)
HESSIAN_INTERPOLATION: Final[str] = "ACTIVATED INTERPOLATION OF THE HESSIAN UP TO"
SCELPHONO_QPOINTS: Final[str] = "THAT PERMITS THE CALCULATION OF MODES AT"
FREQUENCY_HEADER: Final[str] = "MODES         EIGV          FREQUENCIES     IRREP"

# Native CRYSTAL QHA
QHA_HEADER: Final[str] = "QUASI-HARMONIC APPROXIMATION"
QHA_FREQUENCY: Final[str] = "FREQUENCY #"
QHA_VOLUME_ENERGY_TABLE: Final[str] = "SORTING VOLUMES/ENERGIES"
QHA_RESTART: Final[str] = "READING DATA FROM RESTART UNIT"

# Elasticity
ELASTCON_OPTION: Final[str] = "ELASTCON OPTION"
ELAPIEZO_OPTION: Final[str] = "ELAPIEZO OPTION"
ELASTICITY_OPTION_MARKERS: Final[tuple[str, ...]] = (
    ELASTCON_OPTION,
    ELAPIEZO_OPTION,
)
ELASTICITY_RESULTS: Final[str] = "FINAL RESULTS START"
ELASTICITY_CONSTANTS: Final[str] = "SYMMETRIZED ELASTIC CONSTANTS"
ELASTIC_PRESSURE: Final[str] = "ELASTIC PROPERTIES AT PRESSURE"
STRESS_PRESSURE: Final[str] = "PRESSURE IN GIGAPASCAL:"
CELL_VOLUME: Final[str] = "VOLUME OF THE CELL:"
CRYSTAL_DENSITY: Final[str] = "DENSITY OF THE CRYSTAL"
