Bibliographic references
------------------------

.. [#prem_dziewonski_anderson_1981] Adam M. Dziewonski and Don L. Anderson. “Preliminary reference Earth model”. *Physics of the Earth and Planetary Interiors*, **25**, 297-356 (1981). `DOI: 10.1016/0031-9201(81)90046-7 <https://doi.org/10.1016/0031-9201(81)90046-7>`_.

.. [#hasterok_chapman_2011] Derrick Hasterok and David S. Chapman. “Heat production and geotherms for the continental lithosphere”. *Earth and Planetary Science Letters*, **307**, 59-70 (2011). `DOI: 10.1016/j.epsl.2011.04.034 <https://doi.org/10.1016/j.epsl.2011.04.034>`_.

.. [#parsons_sclater_1977] Barry Parsons and John G. Sclater. “An analysis of the variation of ocean floor bathymetry and heat flow with age”. *Journal of Geophysical Research*, **82**, 803-827 (1977). `DOI: 10.1029/JB082i005p00803 <https://doi.org/10.1029/JB082i005p00803>`_.

.. [#katsura_2022] Tomoo Katsura. “A revised adiabatic temperature profile for the mantle”. *Journal of Geophysical Research: Solid Earth*, **127**, e2021JB023562 (2022). `DOI: 10.1029/2021JB023562 <https://doi.org/10.1029/2021JB023562>`_.

.. [#katsura_software_2022] Tomoo Katsura. *Matlab scripts of 'A revised adiabatic temperature profile for the mantle' (Version 1.1.0)*. Zenodo (2022). `DOI: 10.5281/zenodo.5903286 <https://doi.org/10.5281/zenodo.5903286>`_.
