Bibliographic references
------------------------

.. [#nye_1985] John F. Nye. *Physical Properties of Crystals: Their Representation by Tensors and Matrices*. Oxford University Press, Oxford, 2nd edition (1985).

.. [#mouhat_coudert_2014] Felix Mouhat and Francois-Xavier Coudert. “Necessary and sufficient elastic stability conditions in various crystal systems”. *Physical Review B*, **90**, 224104 (2014). `DOI: 10.1103/PhysRevB.90.224104 <https://doi.org/10.1103/PhysRevB.90.224104>`_.

.. [#hill_1952] Rodney Hill. “The elastic behaviour of a crystalline aggregate”. *Proceedings of the Physical Society. Section A*, **65**, 349-354 (1952). `DOI: 10.1088/0370-1298/65/5/307 <https://doi.org/10.1088/0370-1298/65/5/307>`_.

.. [#elate_gaillac_pullumbi_coudert_2016] Romain Gaillac, Pluton Pullumbi, and Francois-Xavier Coudert. “ELATE: an open-source online application for analysis and visualization of elastic tensors”. *Journal of Physics: Condensed Matter*, **28**, 275201 (2016). `DOI: 10.1088/0953-8984/28/27/275201 <https://doi.org/10.1088/0953-8984/28/27/275201>`_.

.. [#stixrude_lithgow_bertelloni_2005] Lars Stixrude and Carolina Lithgow-Bertelloni. “Thermodynamics of mantle minerals - I. Physical properties”. *Geophysical Journal International*, **162**, 610-632 (2005). `DOI: 10.1111/j.1365-246X.2005.02642.x <https://doi.org/10.1111/j.1365-246X.2005.02642.x>`_.
