Bibliographic references
------------------------

.. [#eosfit7_angel_gonzalez_platas_alvaro_2014] Ross J. Angel, Javier Gonzalez-Platas, and Matteo Alvaro. “EosFit7c and a Fortran module (library) for equation of state calculations”. *Zeitschrift fuer Kristallographie*, **229**, 405-419 (2014). `DOI: 10.1515/zkri-2013-1711 <https://doi.org/10.1515/zkri-2013-1711>`_.

.. [#anderson_1995] Orson L. Anderson. *Equations of State of Solids for Geophysics and Ceramic Science*. Oxford University Press, New York (1995).

.. [#stixrude_lithgow_bertelloni_2005] Lars Stixrude and Carolina Lithgow-Bertelloni. “Thermodynamics of mantle minerals - I. Physical properties”. *Geophysical Journal International*, **162**, 610-632 (2005). `DOI: 10.1111/j.1365-246X.2005.02642.x <https://doi.org/10.1111/j.1365-246X.2005.02642.x>`_.
