References
----------

.. [#quantas_2022] G. Ulian and G. Valdrè. “QUANTAS, a Python software for the analysis of solids from ab initio quantum mechanical simulations and experimental data”. *Journal of Applied Crystallography*, **55**, 386-396 (2022). `DOI: 10.1107/S1600576722000085 <https://doi.org/10.1107/S1600576722000085>`_.

.. [#seismic_ulian_valdre_2024] G. Ulian and G. Valdrè. “SEISMIC, a Python-based code of the Quantas package to calculate the phase and group acoustic velocities in crystals”. *Computers & Geosciences*, **188**, 105615 (2024). `DOI: 10.1016/j.cageo.2024.105615 <https://doi.org/10.1016/j.cageo.2024.105615>`_.

.. [#mcquarrie_simon_1997] D. A. McQuarrie and J. D. Simon. *Physical Chemistry: A Molecular Approach*. University Science Books, Sausalito, California (1997).

.. [#anderson_1995] O. L. Anderson. *Equations of State of Solids for Geophysics and Ceramic Science*. *Oxford Monographs on Geology and Geophysics*, **31**, Oxford University Press, New York (1995).

.. [#anderson_masuda_isaak_1995] O. L. Anderson, K. Masuda, and D. G. Isaak. “A new thermodynamic approach for high-pressure physics”. *Physics of the Earth and Planetary Interiors*, **91**, 3-16 (1995). `DOI: 10.1016/0031-9201(95)03044-W <https://doi.org/10.1016/0031-9201(95)03044-W>`_.

.. [#erba_2014] A. Erba. “On combining temperature and pressure effects on structural properties of crystals with standard ab initio techniques”. *Journal of Chemical Physics*, **141**, 124115 (2014). `DOI: 10.1063/1.4896228 <https://doi.org/10.1063/1.4896228>`_.

.. [#erba_shahrokhi_moradian_dovesi_2015] A. Erba, M. Shahrokhi, R. Moradian, and R. Dovesi. “On how differently the quasi-harmonic approximation works for two isostructural crystals: Thermal properties of periclase and lime”. *Journal of Chemical Physics*, **142**, 044114 (2015). `DOI: 10.1063/1.4906422 <https://doi.org/10.1063/1.4906422>`_.

.. [#qha_ulian_valdre_2018] G. Ulian and G. Valdrè. “Equation of state of hexagonal hydroxylapatite (P63) as obtained from density functional theory simulations”. *International Journal of Quantum Chemistry*, **118**, e25553 (2018). `DOI: 10.1002/qua.25553 <https://doi.org/10.1002/qua.25553>`_.

.. [#eosfit7_angel_gonzalez_platas_alvaro_2014] R. J. Angel, J. Gonzalez-Platas, and M. Alvaro. “EosFit7c and a Fortran module (library) for equation of state calculations”. *Zeitschrift für Kristallographie*, **229**, 405-419 (2014). `DOI: 10.1515/zkri-2013-1711 <https://doi.org/10.1515/zkri-2013-1711>`_.

.. [#sjeos_alchagirov_perdew_boettger_albers_fiolhais_2001] A. B. Alchagirov, J. P. Perdew, J. C. Boettger, R. C. Albers, and C. Fiolhais. “Energy and pressure versus volume: Equations of state motivated by the stabilized jellium model”. *Physical Review B*, **63**, 224115 (2001). `DOI: 10.1103/PhysRevB.63.224115 <https://doi.org/10.1103/PhysRevB.63.224115>`_.

.. [#orear_1982] J. Orear. “Least squares when both variables have uncertainties”. *American Journal of Physics*, **50**, 912-916 (1982). `DOI: 10.1119/1.12972 <https://doi.org/10.1119/1.12972>`_.

.. [#boggs_byrd_rogers_schnabel_1992] P. T. Boggs, R. H. Byrd, J. E. Rogers, and R. B. Schnabel. *User's Reference Guide for ODRPACK Version 2.01: Software for Weighted Orthogonal Distance Regression*. NISTIR 4834, National Institute of Standards and Technology, Gaithersburg, MD (1992). `DOI: 10.6028/NIST.IR.4834 <https://doi.org/10.6028/NIST.IR.4834>`_.

.. [#zwolak_boggs_watson_2007] J. W. Zwolak, P. T. Boggs, and L. T. Watson. “Algorithm 869: ODRPACK95: A weighted orthogonal distance regression code with bound constraints”. *ACM Transactions on Mathematical Software*, **33**, Article 27 (2007). `DOI: 10.1145/1268776.1268782 <https://doi.org/10.1145/1268776.1268782>`_.

.. [#berman_1988] R. G. Berman. “Internally-Consistent Thermodynamic Data for Minerals in the System Na2O-K2O-CaO-MgO-FeO-Fe2O3-Al2O3-SiO2-TiO2-H2O-CO2”. *Journal of Petrology*, **29**, 445-522 (1988). `DOI: 10.1093/petrology/29.2.445 <https://doi.org/10.1093/petrology/29.2.445>`_.

.. [#fei_1995] Y. Fei. “Thermal Expansion”. In *Mineral Physics & Crystallography: A Handbook of Physical Constants*, edited by T. J. Ahrens, **2**, 29-44, American Geophysical Union, Washington, DC (1995). `DOI: 10.1029/RF002p0029 <https://doi.org/10.1029/RF002p0029>`_.

.. [#pawley_redfern_holland_1996] A. R. Pawley, S. A. T. Redfern, and T. J. B. Holland. “Volume behavior of hydrous minerals at high pressure and temperature: I. Thermal expansion of lawsonite, zoisite, clinozoisite, and diaspore”. *American Mineralogist*, **81**, 335-340 (1996). `DOI: 10.2138/am-1996-3-407 <https://doi.org/10.2138/am-1996-3-407>`_.

.. [#salje_wruck_thomas_1991] E. K. H. Salje, B. Wruck, and H. Thomas. “Order-parameter saturation and low-temperature extension of Landau theory”. *Zeitschrift für Physik B Condensed Matter*, **82**, 399-404 (1991). `DOI: 10.1007/BF01357186 <https://doi.org/10.1007/BF01357186>`_.

.. [#holland_powell_2011] T. J. B. Holland and R. Powell. “An improved and extended internally consistent thermodynamic dataset for phases of petrological interest, involving a new equation of state for solids”. *Journal of Metamorphic Geology*, **29**, 333-383 (2011). `DOI: 10.1111/j.1525-1314.2010.00923.x <https://doi.org/10.1111/j.1525-1314.2010.00923.x>`_.

.. [#helffrich_connolly_2009] G. R. Helffrich and J. A. D. Connolly. “Physical contradictions and remedies using simple polythermal equations of state”. *American Mineralogist*, **94**, 1616-1619 (2009). `DOI: 10.2138/am.2009.3262 <https://doi.org/10.2138/am.2009.3262>`_.

.. [#kroll_kirfel_heinemann_barbier_2012] H. Kroll, A. Kirfel, R. Heinemann, and B. Barbier. “Volume thermal expansion and related thermophysical parameters in the Mg,Fe olivine solid-solution series”. *European Journal of Mineralogy*, **24**, 935-956 (2012). `DOI: 10.1127/0935-1221/2012/0024-2235 <https://doi.org/10.1127/0935-1221/2012/0024-2235>`_.

.. [#prem_dziewonski_anderson_1981] A. M. Dziewonski and D. L. Anderson. “Preliminary reference Earth model”. *Physics of the Earth and Planetary Interiors*, **25**, 297-356 (1981). `DOI: 10.1016/0031-9201(81)90046-7 <https://doi.org/10.1016/0031-9201(81)90046-7>`_.

.. [#hasterok_chapman_2011] D. Hasterok and D. S. Chapman. “Heat production and geotherms for the continental lithosphere”. *Earth and Planetary Science Letters*, **307**, 59-70 (2011). `DOI: 10.1016/j.epsl.2011.04.034 <https://doi.org/10.1016/j.epsl.2011.04.034>`_.

.. [#parsons_sclater_1977] B. Parsons and J. G. Sclater. “An analysis of the variation of ocean floor bathymetry and heat flow with age”. *Journal of Geophysical Research*, **82**, 803-827 (1977). `DOI: 10.1029/JB082i005p00803 <https://doi.org/10.1029/JB082i005p00803>`_.

.. [#katsura_2022] T. Katsura. “A revised adiabatic temperature profile for the mantle”. *Journal of Geophysical Research: Solid Earth*, **127**, e2021JB023562 (2022). `DOI: 10.1029/2021JB023562 <https://doi.org/10.1029/2021JB023562>`_.

.. [#katsura_software_2022] T. Katsura. *Matlab scripts of 'A revised adiabatic temperature profile for the mantle' (Version 1.1.0)*. Zenodo (2022). `DOI: 10.5281/zenodo.5903286 <https://doi.org/10.5281/zenodo.5903286>`_.

.. [#destefanis_ravoux_cossard_erba_2019] M. Destefanis, C. Ravoux, A. Cossard, and A. Erba. “Thermo-Elasticity of Materials from Quasi-Harmonic Calculations”. *Minerals*, **9**, 16 (2019). `DOI: 10.3390/min9010016 <https://doi.org/10.3390/min9010016>`_.

.. [#erba_mahmoud_belmonte_dovesi_2014] A. Erba, A. Mahmoud, D. Belmonte, and R. Dovesi. “High pressure elastic properties of minerals from ab initio simulations: The case of pyrope, grossular and andradite silicate garnets”. *Journal of Chemical Physics*, **140**, 124703 (2014). `DOI: 10.1063/1.4869144 <https://doi.org/10.1063/1.4869144>`_.

.. [#stixrude_lithgow_bertelloni_2005] L. Stixrude and C. Lithgow-Bertelloni. “Thermodynamics of mantle minerals—I. Physical properties”. *Geophysical Journal International*, **162**, 610-632 (2005). `DOI: 10.1111/j.1365-246X.2005.02642.x <https://doi.org/10.1111/j.1365-246X.2005.02642.x>`_.

.. [#davies_1974] G. F. Davies. “Effective elastic moduli under hydrostatic stress-I. Quasi-harmonic theory”. *Journal of Physics and Chemistry of Solids*, **35**, 1513-1520 (1974). `DOI: 10.1016/S0022-3697(74)80279-9 <https://doi.org/10.1016/S0022-3697(74)80279-9>`_.

.. [#waters_bielawski_2016] T. J. Waters and M. Bielawski. “Isothermal and adiabatic elastic tensors”. *arXiv*, 1605.06548 (2016). `DOI: 10.48550/arXiv.1605.06548 <https://doi.org/10.48550/arXiv.1605.06548>`_.

.. [#wallace_1972] D. C. Wallace. *Thermodynamics of Crystals*. John Wiley & Sons, New York (1972).

.. [#karki_stixrude_clark_warren_ackland_crain_1997] B. B. Karki, L. Stixrude, S. J. Clark, M. C. Warren, G. J. Ackland, and J. Crain. “Structure and elasticity of MgO at high pressure”. *American Mineralogist*, **82**, 51-60 (1997). `DOI: 10.2138/am-1997-1-207 <https://doi.org/10.2138/am-1997-1-207>`_.

.. [#sinogeikin_bass_1999] S. V. Sinogeikin and J. D. Bass. “Single-crystal elasticity of MgO at high pressure”. *Physical Review B*, **59**, R14141-R14144 (1999). `DOI: 10.1103/PhysRevB.59.R14141 <https://doi.org/10.1103/PhysRevB.59.R14141>`_.

.. [#jiang_speziale_duffy_2006] F. Jiang, S. Speziale, and T. S. Duffy. “Elasticity of magnesite and dolomite from a genetic algorithm for inverting Brillouin spectroscopy measurements”. *Physics of the Earth and Planetary Interiors*, **155**, 1-20 (2006). `DOI: 10.1016/j.pepi.2005.08.004 <https://doi.org/10.1016/j.pepi.2005.08.004>`_.

.. [#nye_1985] J. F. Nye. *Physical Properties of Crystals: Their Representation by Tensors and Matrices*. Oxford University Press, Oxford, 2nd edition (1985).

.. [#hill_1952] R. Hill. “The elastic behaviour of a crystalline aggregate”. *Proceedings of the Physical Society. Section A*, **65**, 349-354 (1952). `DOI: 10.1088/0370-1298/65/5/307 <https://doi.org/10.1088/0370-1298/65/5/307>`_.

.. [#elate_gaillac_pullumbi_coudert_2016] R. Gaillac, P. Pullumbi, and F.-X. Coudert. “ELATE: an open-source online application for analysis and visualization of elastic tensors”. *Journal of Physics: Condensed Matter*, **28**, 275201 (2016). `DOI: 10.1088/0953-8984/28/27/275201 <https://doi.org/10.1088/0953-8984/28/27/275201>`_.

.. [#jaeken_cottenier_2016] J. W. Jaeken and S. Cottenier. “Solving the Christoffel equation: Phase and group velocities”. *Computer Physics Communications*, **207**, 445-451 (2016). `DOI: 10.1016/j.cpc.2016.06.014 <https://doi.org/10.1016/j.cpc.2016.06.014>`_.
