References
----------

.. [#anderson_1995] O. L. Anderson. *Equations of State of Solids for Geophysics and Ceramic Science*. *Oxford Monographs on Geology and Geophysics*, **31**, Oxford University Press, New York (1995).

.. [#anderson_masuda_isaak_1995] O. L. Anderson, K. Masuda, and D. G. Isaak. “A new thermodynamic approach for high-pressure physics”. *Physics of the Earth and Planetary Interiors*, **91**, 3-16 (1995). `DOI: 10.1016/0031-9201(95)03044-W <https://doi.org/10.1016/0031-9201(95)03044-W>`_.

.. [#erba_2014] A. Erba. “On combining temperature and pressure effects on structural properties of crystals with standard ab initio techniques”. *Journal of Chemical Physics*, **141**, 124115 (2014). `DOI: 10.1063/1.4896228 <https://doi.org/10.1063/1.4896228>`_.

.. [#erba_shahrokhi_moradian_dovesi_2015] A. Erba, M. Shahrokhi, R. Moradian, and R. Dovesi. “On how differently the quasi-harmonic approximation works for two isostructural crystals: Thermal properties of periclase and lime”. *Journal of Chemical Physics*, **142**, 044114 (2015). `DOI: 10.1063/1.4906422 <https://doi.org/10.1063/1.4906422>`_.
