Bibliographic references
------------------------

.. [#nye_1985] John F. Nye. *Physical Properties of Crystals: Their Representation by Tensors and Matrices*. Oxford University Press, Oxford, 2nd edition (1985).

.. [#jaeken_cottenier_2016] Jan W. Jaeken and Stefaan Cottenier. “Solving the Christoffel equation: Phase and group velocities”. *Computer Physics Communications*, **207**, 445-451 (2016). `DOI: 10.1016/j.cpc.2016.06.014 <https://doi.org/10.1016/j.cpc.2016.06.014>`_.

.. [#seismic_ulian_valdre_2024] Gianfranco Ulian and Giovanni Valdre'. “SEISMIC, a Python-based code of the Quantas package to calculate the phase and group acoustic velocities in crystals”. *Computers & Geosciences*, **188**, 105615 (2024). `DOI: 10.1016/j.cageo.2024.105615 <https://doi.org/10.1016/j.cageo.2024.105615>`_.
