Bibliographic references
------------------------

.. [#stixrude_lithgow_bertelloni_2005] Lars Stixrude and Carolina Lithgow-Bertelloni. “Thermodynamics of mantle minerals - I. Physical properties”. *Geophysical Journal International*, **162**, 610-632 (2005). `DOI: 10.1111/j.1365-246X.2005.02642.x <https://doi.org/10.1111/j.1365-246X.2005.02642.x>`_.

.. [#wallace_1972] D. C. Wallace. *Thermodynamics of Crystals*. John Wiley & Sons, New York (1972).

.. [#barron_klein_1965] T. H. K. Barron and M. L. Klein. “Second-order elastic constants of a solid under stress”. *Proceedings of the Physical Society*, **85**, 523-532 (1965). `DOI: 10.1088/0370-1328/85/3/313 <https://doi.org/10.1088/0370-1328/85/3/313>`_.

.. [#destefanis_ravoux_cossard_erba_2019] Maurizio Destefanis, Corentin Ravoux, Alessandro Cossard, and Alessandro Erba. “Thermo-Elasticity of Materials from Quasi-Harmonic Calculations”. *Minerals*, **9**, 16 (2019). `DOI: 10.3390/min9010016 <https://doi.org/10.3390/min9010016>`_.

.. [#davies_1974] G. F. Davies. “Effective elastic moduli under hydrostatic stress-I. Quasi-harmonic theory”. *Journal of Physics and Chemistry of Solids*, **35**, 1513-1520 (1974). `DOI: 10.1016/S0022-3697(74)80279-9 <https://doi.org/10.1016/S0022-3697(74)80279-9>`_.

.. [#waters_bielawski_2016] T. J. Waters and M. Bielawski. “Isothermal and adiabatic elastic tensors”. *arXiv*, 1605.06548 (2016). `DOI: 10.48550/arXiv.1605.06548 <https://doi.org/10.48550/arXiv.1605.06548>`_.
