References
----------

.. [#karki_stixrude_clark_warren_ackland_crain_1997] B. B. Karki, L. Stixrude, S. J. Clark, M. C. Warren, G. J. Ackland, and J. Crain. “Structure and elasticity of MgO at high pressure”. *American Mineralogist*, **82**, 51-60 (1997). `DOI: 10.2138/am-1997-1-207 <https://doi.org/10.2138/am-1997-1-207>`_.

.. [#sinogeikin_bass_1999] S. V. Sinogeikin and J. D. Bass. “Single-crystal elasticity of MgO at high pressure”. *Physical Review B*, **59**, R14141-R14144 (1999). `DOI: 10.1103/PhysRevB.59.R14141 <https://doi.org/10.1103/PhysRevB.59.R14141>`_.

.. [#jiang_speziale_duffy_2006] F. Jiang, S. Speziale, and T. S. Duffy. “Elasticity of magnesite and dolomite from a genetic algorithm for inverting Brillouin spectroscopy measurements”. *Physics of the Earth and Planetary Interiors*, **155**, 1-20 (2006). `DOI: 10.1016/j.pepi.2005.08.004 <https://doi.org/10.1016/j.pepi.2005.08.004>`_.
