# -*- coding: utf-8 -*-

"""Base class for active Quantas scientific calculators.

Calculators orchestrate validated inputs, numerical work, warnings, results, and
frontend-neutral events without depending on a particular user interface.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from quantas.core.events import (
    Event,
    EventLevel,
    EventRecord,
    NullObserver,
    Observer,
)

from .data import InputData, ResultData, ResultMetadata


class BasicCalculator(ABC):
    """
    Basic class for Quantas calculators.

    Parameters
    ----------
    input_data : InputData
        Input data used by the calculator.
    options : dict or None, optional
        Dictionary containing the options used to control the workflow.
    observer : Observer or None, optional
        Callable object used to receive events emitted during the calculation.

    Attributes
    ----------
    completed : bool
        Flag that is set to ``True`` when the calculation is completed.
    error : str or None
        Error message generated during the workflow, if any.
    warnings : list of str
        Warning messages generated during the workflow.
    result : ResultData or None
        Result generated by the calculator.
    """

    module = "base"
    method = "default"

    def __init__(
        self,
        input_data: InputData,
        options: dict[str, Any] | None = None,
        observer: Observer | None = None,
    ) -> None:
        """
        Constructor for the basic calculator.
        """
        self.input_data = input_data
        self.options = options if options is not None else {}
        self.observer = observer if observer is not None else NullObserver()

        self.completed = False
        self.error: str | None = None
        self.warnings: list[str] = []
        self.events: list[EventRecord] = []
        self.result: ResultData | None = None

    def emit(
        self,
        message: str,
        level: EventLevel = EventLevel.INFO,
        progress: float | None = None,
        data: dict[str, Any] | None = None,
    ) -> None:
        """
        Emit an event from the calculator.

        Parameters
        ----------
        message : str
            Textual message associated with the event.
        level : EventLevel, optional
            Severity or type of the emitted event.
        progress : float or None, optional
            Progress value between 0 and 1.
        data : dict or None, optional
            Optional payload associated with the event.

        Notes
        -----
        Operational ``PROGRESS`` events are forwarded to observers but are not
        stored in the persistent workflow history.
        """
        event = Event(
            message=message,
            level=level,
            progress=progress,
            data=data or {},
        )
        if level != EventLevel.PROGRESS:
            self.events.append(EventRecord.from_event(event))
        self.observer(event)

    def add_warning(self, message: str) -> None:
        """
        Store and emit a warning message.

        Parameters
        ----------
        message : str
            Warning message generated during the workflow.
        """
        self.warnings.append(message)
        self.emit(message, level=EventLevel.WARNING)

    def prepare(self) -> None:
        """
        Prepare the calculator before running the main workflow.

        Derived classes can overwrite this method when preliminary checks,
        allocations, or transformations are required.
        """
        self.emit("Preparing calculation")

    @abstractmethod
    def run(self) -> ResultData:
        """
        Run the main calculation.

        Returns
        -------
        ResultData
            Result generated by the calculator.
        """
        raise NotImplementedError

    def finalize(self) -> ResultData:
        """
        Finalize the calculation and return the result.

        Returns
        -------
        ResultData
            Final result generated by the calculator.
        """
        self.emit("Finalizing calculation", level=EventLevel.DEBUG)

        if self.result is None:
            self.result = ResultData(
                metadata=ResultMetadata(
                    module=self.module,
                    method=self.method,
                ),
                input_data=self.input_data,
                options=self.options,
                warnings=list(self.warnings),
            )

        self.completed = True
        self.emit("Calculation completed", level=EventLevel.RESULT)
        self.result.warnings = list(self.warnings)
        self.result.events = list(self.events)
        return self.result

    def execute(self) -> ResultData:
        """
        Execute the complete workflow.

        Returns
        -------
        ResultData
            Final result generated by the calculator.
        """
        try:
            self.prepare()
            self.result = self.run()
            return self.finalize()
        except Exception as exc:
            self.error = str(exc)
            self.emit(str(exc), level=EventLevel.ERROR)
            raise

    @property
    def results(self) -> dict[str, Any]:
        """
        Return the numerical results stored by the calculator.

        Returns
        -------
        dict
            Dictionary containing the calculated results. If no calculation has
            been completed, an empty dictionary is returned.
        """
        if self.result is None:
            return {}
        return self.result.results
