# -*- coding: utf-8 -*-

"""Frontend-neutral input, metadata, and result envelopes.

These passive containers carry normalized inputs, scientific payloads, warnings,
and persistent workflow events between calculators, frontends, and exporters.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from quantas._version import __version__
from quantas.core.events import EventRecord
from quantas.models.schema import RESULT_SCHEMA_VERSION


@dataclass(slots=True)
class InputData:
    """
    Container for input data read by a Quantas reader.

    Parameters
    ----------
    source : str or Path or None, optional
        Path or textual description of the original source of the input data.
    raw : str or None, optional
        Raw content of the input file, when available.
    data : dict, optional
        Parsed input data.
    """

    source: str | Path | None = None
    raw: str | None = None
    data: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class ResultMetadata:
    """
    Metadata associated with a Quantas calculation.

    Parameters
    ----------
    program : str, optional
        Name of the program that generated the result.
    module : str, optional
        Name of the Quantas module used for the calculation.
    method : str, optional
        Name of the method or workflow used by the module.
    version : str, optional
        Quantas version used to generate the result.
    created_by : str or None, optional
        Name of the user or routine that generated the result.
    created_at : datetime, optional
        Date and time at which the result was created.
    schema_version : str, optional
        Version of the internal result schema.
    """

    program: str = "quantas"
    module: str = "unknown"
    method: str = "unknown"
    version: str = __version__
    created_by: str | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    schema_version: str = RESULT_SCHEMA_VERSION


@dataclass(slots=True)
class ResultData:
    """
    Container for the final result of a Quantas calculation.

    Parameters
    ----------
    metadata : ResultMetadata
        Metadata describing how the result was generated.
    input_data : InputData or None, optional
        Input data used by the calculator.
    options : dict, optional
        Options used to control the workflow.
    results : dict, optional
        Numerical or textual results generated by the workflow.
    warnings : list of str, optional
        Warning messages collected during the calculation.
    events : list of EventRecord, optional
        Persistent workflow event log.
    """

    metadata: ResultMetadata
    input_data: InputData | None = None
    options: dict[str, Any] = field(default_factory=dict)
    results: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    events: list[EventRecord] = field(default_factory=list)

    def add_result(self, key: str, value: Any) -> None:
        """
        Store a calculated result.

        This method provides a small convenience wrapper around the internal
        results dictionary and can be used by calculators to add numerical or
        textual data to the result container.

        Parameters
        ----------
        key : str
            Name associated with the stored result.
        value : Any
            Value to be stored.
        """
        self.results[key] = value

    def add_warning(self, message: str) -> None:
        """
        Store a warning message.

        Warning messages are collected during the execution of a workflow and can
        be reported to the user at the end of the calculation or stored in the
        output file.

        Parameters
        ----------
        message : str
            Warning message to be stored.
        """
        self.warnings.append(message)
