# -*- coding: utf-8 -*-

"""Schema definitions for native Quantas result containers.

The schema version is independent from the Quantas package version.  It changes
only when the structure or scientific interpretation of persisted results
changes incompatibly.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Final

RESULT_SCHEMA_VERSION: Final[str] = "2.0"
REQUIRED_RESULT_GROUPS: Final[tuple[str, ...]] = (
    "metadata",
    "input",
    "options",
    "results",
    "diagnostics",
    "events",
)


@dataclass(frozen=True, slots=True)
class ResultSchema:
    """Description of the native Quantas result schema.

    Parameters
    ----------
    version : str, optional
        Schema version identifier.
    required_groups : tuple of str, optional
        Required top-level groups in a native result file.
    """

    version: str = RESULT_SCHEMA_VERSION
    required_groups: tuple[str, ...] = REQUIRED_RESULT_GROUPS

    def validate(self, container: Any, expected_module: str | None = None) -> None:
        """Validate a mapping-like native Quantas result container.

        Parameters
        ----------
        container : Any
            Open HDF5 file or mapping-like object exposing keys and groups.
        expected_module : str or None, optional
            Module identifier expected in ``metadata``.

        Raises
        ------
        ValueError
            If required groups or metadata attributes are missing or invalid.
        """
        missing = [name for name in self.required_groups if name not in container]
        if missing:
            raise ValueError(
                "Missing required Quantas result groups: " + ", ".join(missing)
            )

        metadata = container["metadata"].attrs
        program = _as_text(metadata.get("program", ""))
        if program != "quantas":
            raise ValueError("The selected result was not generated by Quantas.")

        version = _as_text(metadata.get("schema_version", ""))
        if version != self.version:
            raise ValueError(
                f"Unsupported Quantas result schema '{version}'; "
                f"expected '{self.version}'."
            )

        if expected_module is not None:
            module = _as_text(metadata.get("module", ""))
            if module != expected_module:
                raise ValueError(
                    f"The selected result contains module '{module}', "
                    f"not '{expected_module}'."
                )


def validate_result_schema(
    container: Any,
    expected_module: str | None = None,
) -> None:
    """Validate the current native Quantas result schema.

    Parameters
    ----------
    container : Any
        Open HDF5 file or mapping-like result container.
    expected_module : str or None, optional
        Expected module identifier.

    Raises
    ------
    ValueError
        If the result does not satisfy the current schema.
    """
    ResultSchema().validate(container, expected_module=expected_module)


def _as_text(value: Any) -> str:
    """Return a scalar HDF5 attribute as text."""
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return str(value)
