#!/usr/bin/env bash

# Remove disposable files produced by Quantas validation and local tooling.
#
# The script is intentionally conservative:
# - it resolves the repository root from its own location under tools/;
# - it never invokes `git clean`;
# - it refuses to remove paths containing Git-tracked files;
# - it does not touch committed documentation assets under docs/source/;
# - it preserves a normal developer virtual environment such as .venv/.

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

DRY_RUN=0
KEEP_LOGS=0
KEEP_VALIDATION_VENV=0

usage() {
    cat <<'USAGE'
Usage: tools/post_validation_cleanup.sh [OPTIONS]

Remove disposable artifacts created by tools/validate_release.sh and related
local checks, while preserving source files and committed documentation assets.

Options:
  -n, --dry-run               Show what would be removed without deleting it.
      --keep-logs             Preserve the validation/ directory and its logs.
      --keep-validation-venv  Preserve .venv-validation/.
  -h, --help                  Show this help message.

Examples:
  tools/post_validation_cleanup.sh --dry-run
  tools/post_validation_cleanup.sh
  tools/post_validation_cleanup.sh --keep-logs
USAGE
}

while (($#)); do
    case "$1" in
        -n|--dry-run)
            DRY_RUN=1
            ;;
        --keep-logs)
            KEEP_LOGS=1
            ;;
        --keep-validation-venv)
            KEEP_VALIDATION_VENV=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            printf 'Unknown option: %s\n\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

note() {
    printf '%s\n' "$*"
}

[[ -f "${ROOT}/pyproject.toml" ]] || die "${ROOT} is not a Quantas source root (pyproject.toml missing)."
[[ -d "${ROOT}/src/quantas" ]] || die "${ROOT} is not a Quantas source root (src/quantas missing)."
[[ "${ROOT}" != "/" ]] || die "Refusing to operate on the filesystem root."

VALIDATION_VENV="${ROOT}/.venv-validation"
if [[ "${VIRTUAL_ENV:-}" == "${VALIDATION_VENV}" && ${KEEP_VALIDATION_VENV} -eq 0 ]]; then
    die "The validation environment is active. Run 'deactivate' before cleanup."
fi

GIT_AVAILABLE=0
if git -C "${ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    GIT_AVAILABLE=1
fi

removed_count=0
skipped_count=0

relative_to_root() {
    local path=$1
    if [[ "${path}" == "${ROOT}" ]]; then
        printf '.\n'
    else
        printf '%s\n' "${path#"${ROOT}/"}"
    fi
}

assert_untracked_path() {
    local path=$1
    local relative
    local tracked

    ((GIT_AVAILABLE == 1)) || return 0

    relative="$(relative_to_root "${path}")"
    tracked="$(git -C "${ROOT}" ls-files -- "${relative}" 2>/dev/null || true)"
    if [[ -n "${tracked}" ]]; then
        printf 'Refusing to remove %s because it contains tracked files:\n%s\n' \
            "${relative}" "${tracked}" >&2
        return 1
    fi
}

remove_path() {
    local path=$1
    local relative

    if [[ ! -e "${path}" && ! -L "${path}" ]]; then
        ((skipped_count += 1))
        return 0
    fi

    relative="$(relative_to_root "${path}")"
    assert_untracked_path "${path}" || die "Cleanup stopped before deleting tracked content."

    if ((DRY_RUN == 1)); then
        printf '[dry-run] remove %s\n' "${relative}"
    else
        rm -rf -- "${path}"
        printf 'removed %s\n' "${relative}"
    fi
    ((removed_count += 1))
}

note "=== Quantas post-validation cleanup ==="
note "Root: ${ROOT}"
if ((DRY_RUN == 1)); then
    note "Mode: dry run"
fi

# Dedicated validation environment.
if ((KEEP_VALIDATION_VENV == 0)); then
    remove_path "${VALIDATION_VENV}"
else
    note "preserved .venv-validation/"
fi

# Build, packaging, documentation, testing, and coverage outputs.
for relative in \
    build \
    dist \
    docs/_build \
    .pytest_cache \
    .mypy_cache \
    .ruff_cache \
    .hypothesis \
    htmlcov \
    .coverage \
    coverage.xml; do
    remove_path "${ROOT}/${relative}"
done

# Parallel coverage files, for example .coverage.worker-1.
while IFS= read -r -d '' path; do
    remove_path "${path}"
done < <(
    find "${ROOT}" \
        -maxdepth 1 \
        -type f \
        -name '.coverage.*' \
        -print0
)

# Metadata generated by editable installs and package builds.
while IFS= read -r -d '' path; do
    remove_path "${path}"
done < <(
    find "${ROOT}" \
        \( \
            -path "${ROOT}/.git" -o \
            -path "${ROOT}/.venv" -o \
            -path "${ROOT}/venv" -o \
            -path "${ROOT}/env" \
        \) -prune -o \
        -type d \
        -name '*.egg-info' \
        -print0
)

# Python caches produced in project-controlled source and tooling directories.
for search_root in \
    "${ROOT}/src" \
    "${ROOT}/tests" \
    "${ROOT}/tools" \
    "${ROOT}/examples" \
    "${ROOT}/docs"; do
    [[ -d "${search_root}" ]] || continue

    while IFS= read -r -d '' path; do
        remove_path "${path}"
    done < <(
        find "${search_root}" \
            -type d \
            -name '__pycache__' \
            -prune \
            -print0
    )

    while IFS= read -r -d '' path; do
        remove_path "${path}"
    done < <(
        find "${search_root}" \
            -type d \
            -name '__pycache__' \
            -prune -o \
            -type f \
            \( -name '*.pyc' -o -name '*.pyo' \) \
            -print0
    )
done

# Reports written by tools/check_architecture.py during validation.
remove_path "${ROOT}/project_internal/checks/architecture.json"
remove_path "${ROOT}/project_internal/checks/architecture.md"

if ((DRY_RUN == 0)); then
    rmdir "${ROOT}/project_internal/checks" 2>/dev/null || true
    rmdir "${ROOT}/project_internal" 2>/dev/null || true
fi

# Maintainer validation logs are disposable by default but can be retained.
if ((KEEP_LOGS == 0)); then
    remove_path "${ROOT}/validation"
else
    note "preserved validation/"
fi

note "Cleanup targets removed: ${removed_count}"

if ((GIT_AVAILABLE == 1)); then
    note ""
    note "Git status after cleanup:"
    git -C "${ROOT}" status --short --branch
else
    note "No Git worktree detected; Git status was skipped."
fi

note "=== Cleanup completed ==="

