# -*- coding: utf-8 -*-

"""Reusable numerical mathematics for Quantas scientific workflows."""

from .derivative import (
    LenError,
    derivative,
    polynomial_derivative,
    polynomial_derivative_from_coefficients,
    relative_derivative,
)
from .frechet import matrix_exponential_frechet
from .fitting import (
    BaseFitModel,
    CallableFitModel,
    CovarianceScaling,
    EffectiveVarianceFitter,
    EffectiveVarianceOptions,
    FitDiagnostics,
    FitMethod,
    FitObservations,
    FitOptions,
    FitQuality,
    FitResult,
    FitSolver,
    FitStatus,
    SOLVER_DEBUG_METADATA_KEY,
    FittedModel,
    LeastSquaresFitter,
    LeastSquaresOptions,
    OLSOptions,
    ODROptions,
    SolverOptions,
    WLSOptions,
    default_solver_options,
    MappedFitModel,
    ODRBackendUnavailableError,
    ODRDifferenceScheme,
    OrthogonalDistanceFitter,
    OrthogonalDistanceOptions,
    ParameterDefinition,
    ParameterMap,
    ParameterSet,
    ParameterState,
    least_squares_fit,
    odr_backend_available,
    resolve_mapped_fit_result,
)

__all__ = [
    "LenError",
    "derivative",
    "polynomial_derivative",
    "polynomial_derivative_from_coefficients",
    "relative_derivative",
    "matrix_exponential_frechet",
    "BaseFitModel",
    "CallableFitModel",
    "CovarianceScaling",
    "EffectiveVarianceFitter",
    "EffectiveVarianceOptions",
    "FitDiagnostics",
    "FitMethod",
    "FitObservations",
    "FitOptions",
    "FitQuality",
    "FitResult",
    "FitSolver",
    "FitStatus",
    "SOLVER_DEBUG_METADATA_KEY",
    "FittedModel",
    "LeastSquaresFitter",
    "LeastSquaresOptions",
    "OLSOptions",
    "ODROptions",
    "SolverOptions",
    "WLSOptions",
    "default_solver_options",
    "MappedFitModel",
    "ODRBackendUnavailableError",
    "ODRDifferenceScheme",
    "OrthogonalDistanceFitter",
    "OrthogonalDistanceOptions",
    "ParameterDefinition",
    "ParameterMap",
    "ParameterSet",
    "ParameterState",
    "least_squares_fit",
    "odr_backend_available",
    "resolve_mapped_fit_result",
]
